//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJ_RYAN.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class login
    {
        [Display(Name = "Id")]
        public int id_login { get; set; }
        [Display(Name = "Nome")]
        public string nome { get; set; }
        [Display(Name = "Senha")]
        public string senha { get; set; }
        [Display(Name = "Data da alteração")]
        public Nullable<System.DateTime> data_cadastro { get; set; }
        [Display(Name = "Login")]
        public string login_email { get; set; }
    }
}
